spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/tasklist
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
